let brands = [
    { id: 1, image: 'Samsung.jpg', name: "Samsung" },
    { id: 2, image: 'Xiaomi.png', name: "Xiaomi" },
    { id: 3, image: 'Apple.png', name: "Apple" },
    { id: 4, image: 'HP.png', name: "HP" },
    { id: 5, image: 'Bosch.jpg', name: "Bosch" },
    { id: 7, image: 'Microsoft.png', name: "Microsoft" },
]

let products = [
    { 
        id: Math.random().toString().slice(2, 10),
        brand_id: 3,
        name: "Apple iPhone 11 pro",
        price: 767,
        image: "./images/products/AppleiPhone11-removebg-preview (1).png",
        liked: false,
        cart: 0,
        description: [
            'Экран: 6.1" (1792x828)',
            'Оперативная память: 4 ГБ',
            'Память: 128 ГБ',
            'Двойная камера: 12 МП, 12 МП',
            'Аккумулятор: 3110 мА·ч',
            'Процессор: Apple A13 Bionic',
            'SIM-карты: 2 (nano SIM+eSIM)',
            'Операционная система: iOS 13',
            'Беспроводные интерфейсы: NFC, Wi-Fi, Bluetooth 5.0',
            'Интернет: 4G LTE',
            'Степень защиты: IP68',
            'Вес: 194 г',
        ]
    },
    { 
        id: Math.random().toString().slice(2, 10),
        brand_id: 3,
        name: "Apple iPhone SE 2020",
        price: 499,
        image: "./images/products/AppleiPhoneSE-removebg-preview.png",
        liked: false,
        cart: 0,
        description: [
            'экран: 4.7" (1334×750)',
            'оперативная память: 3 ГБ',
            'память: 128 ГБ',
            'камера: 12 МП',
            'аккумулятор: 1821 мА·ч',
            'процессор: Apple A13 Bionic',
            'SIM-карты: 2 (nano SIM+eSIM)',
            'операционная система: iOS 13',
            'беспроводные интерфейсы: NFC, Wi-Fi, Bluetooth 5.0',
            'интернет: 4G LTE',
            'степень защиты: IP67',
            'вес: 148 г',

        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 3,
        name: "Apple iPhone 12 Pro",
        price: 1452,
        image: "./images/products/AppleiPhone12Pro-removebg-preview (1).png",
        cart: 0,
        description: [
            'Экран: 6.1" (2532x1170)',
            'Оперативная память: 6 ГБ',
            'Память: 256 ГБ',
            '3 камеры: 12 МП, 12 МП, 12 МП',
            'Аккумулятор: 2815 мА·ч',
            'Процессор: Apple A14 Bionic',
            'SIM-карты: 2 (nano SIM+eSIM)',
            'Операционная система: iOS 14',
            'Беспроводные интерфейсы: NFC, Wi-Fi, Bluetooth 5.0',
            'Интернет: 4G LTE, 5G',
            'Степень защиты: IP68',
            'Вес: 187 г',
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 3,
        name: "Apple iPhone XS ",
        price: 700,
        image: "./images/products/iPhone XS.png",
        liked: false,
        cart: 0,
        description: [
            'Фотокамера (Мп) 12 + 12 (двойная)',
            'Разрешение видеосъемки (пикс) 3840 x 2160',
            'Процессор Apple A12 Bionic',
            'Количество ядер 6',
            'Оперативная память (Гб) 4'
        ]
    },
    { 
        id: Math.random().toString().slice(2, 10),
        brand_id: 3,
        name: "Apple MacBook Air 13",
        price: 1107,
        image: "./images/products/AppleMacBookPro13Late.png",
        liked: false,
        cart: 0,
        description: [
            'экран: 13.3" (2560x1600)',
            'матрица: IPS',
            'процессор: Apple M1 (8x3200 МГц)',
            'оперативная память: 8 ГБ',
            'накопитель: SSD 256 ГБ',
            'встроенная видеокарта: Apple graphics 7-core',
            'разъемы: микрофон/наушники Combo, Thunderbolt/USB 4 x 2',
            'фунционал USB Type-C: Power Delivery, Thunderbolt 3, Thunderbolt 4',
            'беспроводная связь: Wi-Fi 802.11ax, Bluetooth 5.0',
            'емкость аккумулятора: 49.9 Вт⋅ч',
            'время работы от аккумулятора: 18 ч',
            'операционная система: macOS',
            'pазмеры: 304.1x212.4x16.1 мм',
            'вес: 1.29 кг',

        ]
    },
    { 
        id: Math.random().toString().slice(2, 10),
        brand_id: 3,
        name: "Apple iPhone 7",
        price: 250,
        image: "./images/products/iphone-7.png",
        liked: false,
        cart: 0,
        description: [
            'экран: 13.3" (2560x1600)',
            'матрица: IPS',
            'процессор: Apple Bionic A14   (8x3200 МГц)',
            'оперативная память: 4 ГБ',
            'Количество ядер 4'
        ]
    },
    { 
        id: Math.random().toString().slice(2, 10),
        brand_id: 3,
        name: "Apple MacBook Pro 13",
        price: 2120,
        image: "./images/products/AppleMacBookPro.png",
        liked: false,
        cart: 0,
        description: [
            'экран: 13.3" (2560x1600)',
            'матрица: IPS',
            'процессор: Apple M1 (8x3200 МГц)',
            'оперативная память: 16 ГБ',
            'накопитель: SSD 512 ГБ',
            'встроенная видеокарта: Apple graphics 8-core',
            'разъемы: микрофон/наушники Combo, Thunderbolt/USB 4 x 2',
            'фунционал USB Type-C: Power Delivery, Thunderbolt 3, Thunderbolt 4',
            'беспроводная связь: Wi-Fi 802.11ax, Bluetooth 5.0',
            'емкость аккумулятора: 58.2 Вт⋅ч',
            'время работы от аккумулятора: 20 ч',
            'операционная система: macOS',
            'pазмеры: 304.1x212.4x15.6 мм',
            'вес: 1.4 кг',

        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 1,
        name: "Galaxy S20 Ultra",
        price: 1299,
        image: "./images/products/GalaxyS20.png",
        liked: false,
        cart: 0,
        description: [
            'экран: 6.2" (2400x1080) 120 Гц',
            'оперативная память: 8 ГБ', 'память: 128 ГБ',
            '3 камеры: 64 МП, 12 МП, 12 МП',
            'аккумулятор: 4000 мА·ч',
            'процессор: Samsung Exynos 2100',
            'SIM-карты: 2 (nano SIM+eSIM)',
            'операционная система: Android 11',
            'беспроводные интерфейсы: NFC, Wi-Fi, Bluetooth 5.1',
            'интернет: 4G LTE, 5G',
            'степень защиты: IP68',
            'вес: 171 г'
        ]
    },
    
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 1,
        name: "Samsung Galaxy S21",
        price: 875,
        image: "./images/products/GalaxyS215G,.png",
        liked: false,
        cart: 0,
        description: [
            'экран: 6.2" (2400x1080) 120 Гц',
            'оперативная память: 8 ГБ',
            'память: 128 ГБ',
            '3 камеры: 64 МП, 12 МП, 12 МП',
            'аккумулятор: 4000 мА·ч',
            'процессор: Samsung Exynos 2100',
            'SIM-карты: 2 (nano SIM+eSIM)',
            'операционная система: Android 11',
            'беспроводные интерфейсы: NFC, Wi-Fi, Bluetooth 5.1',
            'интернет: 4G LTE, 5G',
            'степень защиты: IP68',
            'вес: 171 г',
        ]
    },
    { 
        id: Math.random().toString().slice(2, 10),
        brand_id: 2,
        name: "Xiaomi Poco X3 Pro",
        price: 140,
        image: "./images/products/СмартфонXiaomiPoco.png",
        liked: false,
        cart: 0,
        description: [
            'экран: 6.67" (2400x1080) 120 Гц',
            'оперативная память: 6 ГБ',
            'память: 128 ГБ, слот для карты памяти',
            '4 камеры: 48 МП, 8 МП, 2 МП, 2 МП',
            'аккумулятор: 5160 мА·ч',
            'процессор: Qualcomm Snapdragon 860',
            'SIM-карты: 2 (nano SIM)',
            'операционная система: Android 11',
            'беспроводные интерфейсы: NFC, Wi-Fi, Bluetooth 5.0',
            'интернет: 4G LTE',
            'степень защиты: IP53',
            'вес: 215 г',
        ]
    },
    { 
        id: Math.random().toString().slice(2, 10),
        brand_id: 2,
        name: "Xiaomi Redmi Note 9",
        price: 285,
        image: "./images/products/XiaomiRedmiNot9.png",
        liked: false,
        cart: 0,
        description: [
            'экран: 5" (1920×1080)',
            'оперативная память: 3 ГБ',
            'память: 64 ГБ, слот для карты памяти',
            'камера: 13 МП',
            'аккумулятор: 3260 мА·ч',
            'процессор: Qualcomm Snapdragon 808 MSM8992',
            'SIM-карты: 2 (micro SIM+nano SIM)',
            'операционная система: Android 6.0',
            'беспроводные интерфейсы: Wi-Fi, Bluetooth 4.1',
            'интернет: 4G LTE',
            'вес: 133 г',
        ]
    },
    

    { 
        id: Math.random().toString().slice(2, 10),
        brand_id: 1,
        name: "Samsung Galaxy A12",
        price: 173,
        image: "./images/products/SamsungGalaxyA12.png",
        liked: false,
        cart: 0,
        description: [
            'Экран: 6.5" (1600x720) 60 Гц',
            'Оперативная память: 4 ГБ',
            'Память: 64 ГБ, слот для карты памяти',
            '4 камеры: 48 МП, 5 МП, 2 МП, 2 МП',
            'Аккумулятор: 5000 мА·ч',
            'Процессор: MediaTek Helio P35 (MT6765)',
            'SIM-карты: 2 (nano SIM)',
            'Операционная система: Android 10',
            'Беспроводные интерфейсы: NFC, Wi-Fi, Bluetooth 5.0',
            'Интернет: 4G LTE',
            'Вес: 205 г',
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 2,
        name: "Xiaomi Redmi Note 10",
        price: 195,
        image: "./images/products/XiaomiRedmiNote10.png",
        liked: false,
        cart: 0,
        description: [
            'Экран: 6.43" (2400x1080)',
            'Оперативная память: 4 ГБ',
            'Память: 64 ГБ, слот для карты памяти',
            '4 камеры: 48 МП, 8 МП, 2 МП, 2 МП',
            'Аккумулятор: 5000 мА·ч',
            'SIM-карты: 2 (nano SIM)',
            'Операционная система: Android 11',
            'Беспроводные интерфейсы: Wi-Fi, Bluetooth 5.0',
            'Интернет: 4G LTE',
            'Степень защиты: IP53',
            'Вес: 179 г',
        ]
    },
    
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 2,
        name: "HUAWEI P40 Lite",
        price: 256,
        image: "./images/products/HUAWEIP40.png",
        liked: false,
        cart: 0,
        description: [
            'Экран: 6.4" (2310x1080)',
            'Оперативная память: 6 ГБ',
            'Память: 128 ГБ, слот для карты памяти',
            '4 камеры: 48 МП, 8 МП, 2 МП, 2 МП',
            'Аккумулятор: 4200 мА·ч',
            'Процессор: HiSilicon Kirin 810',
            'SIM-карты: 2',
            'Операционная система: Android 10',
            'Беспроводные интерфейсы: NFC, Wi-Fi, Bluetooth 5.0',
            'Интернет: 4G LTE',
            'Вес: 183 г',
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 2,
        name: "HUAWEI P smart 2021",
        price: 198,
        image: "./images/products/HUAWEIPsmart.png",
        liked: false,
        cart: 0,
        description: [
            'Экран: 6.67" (2400x1080)',
            'Оперативная память: 4 ГБ',
            'Память: 128 ГБ, слот для карты памяти',
            '4 камеры: 48 МП, 8 МП, 2 МП, 2 МП',
            'Аккумулятор: 5000 мА·ч',
            'Процессор: HiSilicon Kirin 710',
            'SIM-карты: 2 (nano SIM)',
            'Операционная система: Android 10',
            'Беспроводные интерфейсы: NFC, Wi-Fi, Bluetooth 5.1',
            'Интернет: 4G LTE',
            'Вес: 206 г',
        ]    
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 2,
        name: "HUAWEI Nova 5T",
        price: 316,
        image: "./images/products/HUAWEINova.png",
        liked: false,
        cart: 0,
        description: [
            'экран: 6.26" (2340×1080) 60 Гц',
            'оперативная память: 6 ГБ',
            'память: 128 ГБ',
            '4 камеры: 48 МП, 16 МП, 2 МП, 2 МП',
            'аккумулятор: 3750 мА·ч',
            'процессор: HiSilicon Kirin 980',
            'SIM-карты: 2 (nano SIM)',
            'операционная система: Android 9.0',
            'беспроводные интерфейсы: NFC, Wi-Fi, Bluetooth 5.0',
            'интернет: 4G LTE',
            'вес: 174 г',
        ]    
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 2,
        name: "HUAWEI Mate 40 Pro",
        price: 115,
        image: "./images/products/HUAWEIMatePro.png",
        liked: false,
        cart: 0,
        description: [
            'экран: 6.76" (2772x1344) 90 Гц',
            'оперативная память: 8 ГБ',
            'память: 256 ГБ, слот для карты памяти',
            '3 камеры: 50 МП, 20 МП, 12 МП',
            'аккумулятор: 4400 мА·ч',
            'процессор: Huawei Kirin 9000',
            'SIM-карты: 2 (nano SIM)',
            'операционная система: Android 10',
            'беспроводные интерфейсы: NFC, Wi-Fi, Bluetooth 5.2',
            'интернет: 4G LTE, 5G',
            'степень защиты: IP68',
            'вес: 212 г',

        ]    
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 2,
        name: "HUAWEI P30 Pro",
        price: 734,
        image: "./images/products/HUAWEIP30Pro.png",
        liked: false,
        cart: 0,
        description: [
            'экран: 6.47" (2340×1080) 60 Гц',
            'оперативная память: 8 ГБ',
            'память: 256 ГБ, слот для карты памяти',
            '4 камеры: 40 МП, 20 МП, 8 МП',
            'аккумулятор: 4200 мА·ч',
            'процессор: HiSilicon Kirin 980',
            'SIM-карты: 2 (nano SIM)',
            'операционная система: Android 9.0',
            'беспроводные интерфейсы: NFC, Wi-Fi, Bluetooth 5.0',
            'интернет: 4G LTE',
            'степень защиты: IP68',
            'вес: 192 г',

        ]    
    },

    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 4,
        name: "HP OMEN AMD 15.6",
        price: 1462,
        image: "./images/products/HPOMEN15-en.png",
        liked: false,
        cart: 0,
        description: [
            'Игровой ноутбук',
            'Экран: 15.6" (1920x1080)',
            'Матрица: IPS',
            'Процессор: AMD Ryzen 7 4800H (8x2900 МГц)',
            'Оперативная память: 16 ГБ DDR4 3200 МГц',
            'Накопитель: SSD 512 ГБ',
            'Дискретная видеокарта: NVIDIA GeForce RTX 2060 (6 ГБ)',
            'Разъемы: USB 3.2 Gen1 Type A x 3, USB 3.2 Gen1 Type-С, выход HDMI, выход Mini DisplayPort, микрофон/наушники Combo, Ethernet - RJ-45',
            'Беспроводная связь: Wi-Fi 802.11ac, Bluetooth 5.0',
            'Емкость аккумулятора: 70.9 Вт⋅ч',
            'Время работы от аккумулятора: 11 ч',
            'Операционная система: Windows 10 Home',
            'Pазмеры: 357.9x239.7x22.5 мм',
            'Вес: 2.47 кг',
        ]    
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 4,
        name: "HP Pavilion Intel 15.6",
        price: 993,
        image: "./images/products/HPPavilion15-eg.png",
        liked: false,
        cart: 0,
        description: [
            'Экран: 15.6" (1920x1080)',
            'Матрица: IPS',
            'Процессор: Intel Core i5 1135G7 (4x2400 МГц)',
            'Оперативная память: 8 ГБ DDR4 3200 МГц',
            'Накопитель: SSD 512 ГБ',
            'Дискретная видеокарта: NVIDIA GeForce MX350 (2 ГБ)',
            'Разъемы: USB 3.2 Gen1 Type A x 2, USB 3.2 Gen2 Type-С, выход HDMI, микрофон/наушники Combo',
            'Беспроводная связь: Wi-Fi 802.11ac, Bluetooth 5.0',
            'Емкость аккумулятора: 41 Вт⋅ч',
            'Время работы от аккумулятора: 8.5 ч',
            'Операционная система: Windows 10 Home',
            'Pазмеры: 360.2x234x17.9 мм',
            'Вес: 1.75 кг',
        ]    
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 4,
        name: "HP Spectre 13-v006ur",
        price: 1400,
        image: "./images/products/HPSpectre.png",
        liked: false,
        cart: 0,
        description: [
            'экран: 13.3" (1920x1080)',
            'матрица: IPS',
            'процессор: Intel Core i5 6200U (2x2300 МГц)',
            'оперативная память: 8 ГБ LPDDR3 1866 МГц',
            'накопитель: 256 ГБ',
            'встроенная видеокарта: Intel HD Graphics 520',
            'разъемы: USB 3.1 Type-С, Thunderbolt 3 x 2, микрофон/наушники Combo',
            'фунционал USB Type-C: Thunderbolt 3',
            'беспроводная связь: Wi-Fi 802.11ac, Bluetooth 4.2',
            'время работы от аккумулятора: 8 ч',
            'операционная система: Windows 10 Home',
            'pазмеры: 325.1x229.4x10.4 мм',
            'вес: 1.1 кг',
        ]    
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 4,
        name: "HP EliteBook 2021",
        price: 998,
        image: "./images/products/HPEliteBook.png",
        liked: false,
        cart: 0,
        description: [
            'экран: 13.3" (1920x1080)',
            'процессор: Intel Core i5 8250U (4x1600 МГц)',
            'оперативная память: 16 ГБ DDR4 2400 МГц',
            'накопитель: 512 ГБ',
            'встроенная видеокарта: Intel UHD Graphics 620',
            'разъемы: USB 3.1 Type A x 2, выход HDMI, Thunderbolt 3, интерфейс док-станции, микрофон/наушники Combo',
            'фунционал USB Type-C: Thunderbolt 3',
            'беспроводная связь: Wi-Fi 802.11ac, Bluetooth 4.2',
            'емкость аккумулятора: 50 Вт⋅ч',
            'время работы от аккумулятора: 13.75 ч',
            'операционная система: Windows 10 Pro',
            'pазмеры: 310x229.3x17.7 мм',
            'вес: 1.33 кг',
        ]    
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 4,
        name: "HP ZBook 15 2021",
        price: 1870,
        image: "./images/products/HPZBook15.png",
        liked: false,
        cart: 0,
        description: [
            'экран: 13.3" (1920x1080)',
            'процессор: Intel Core i5 8250U (4x1600 МГц)',
            'оперативная память: 16 ГБ DDR4 2400 МГц',
            'накопитель: 512 ГБ',
            'встроенная видеокарта: Intel UHD Graphics 620',
            'разъемы: USB 3.1 Type A x 2, выход HDMI, Thunderbolt 3, интерфейс док-станции, микрофон/наушники Combo',
            'фунционал USB Type-C: Thunderbolt 3',
            'беспроводная связь: Wi-Fi 802.11ac, Bluetooth 4.2',
            'емкость аккумулятора: 50 Вт⋅ч',
            'время работы от аккумулятора: 13.75 ч',
            'операционная система: Windows 10 Pro',
            'pазмеры: 310x229.3x17.7 мм',
            'вес: 1.33 кг',
        ]    
    },
    
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 7,
        name: "Microsoft Surface Laptop",
        price: 900,
        image: "./images/products/SurfaceLaptop313.png",
        liked: false,
        cart: 0,
        description: [
            'экран: 13.5" (2256x1504)',
            'процессор: Intel Core i5 1035G7 (3700 МГц)',
            'оперативная память: 8 ГБ LPDDR4X 3733 МГц',
            'накопитель: 128 ГБ',
            'встроенная видеокарта: Intel Iris Plus Graphics',
            'беспроводная связь: Wi-Fi 802.11ax, Bluetooth 5.0',
            'время работы от аккумулятора: 11.5 ч',
            'операционная система: Windows 10 Home',
            'pазмеры: 223x308x14.5 мм',
        ]    
    },


    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 7,
        name: "Microsoft Surface Laptop",
        price: 799,
        image: "./images/products/SurfaceLaptopGo.png",
        liked: false,
        cart: 0,
        description: [
            'экран: 12.4" (1536x1024)',
            'процессор: Intel Core i5-1035G1 (4x1000 МГц)',
            'оперативная память: 8 ГБ LPDDR4X 3733 МГц',
            'накопитель: SSD 128 ГБ',
            'встроенная видеокарта: Intel UHD Graphics',
            'разъемы: USB 2.0 Type A, USB 3.1 Type-С, микрофон/наушники Combo',
            'беспроводная связь: Wi-Fi 802.11ax, Bluetooth 5.0',
            'время работы от аккумулятора: 13 ч',
            'операционная система: Windows 10 Home',
            'pазмеры: 278.18x205.67x15.69 мм',
            'вес: 1.11 кг',
        ]    
    },
    

    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 7,
        name: "Microsoft Surface Pro 7",
        price: 150,
        image: "./images/products/MicrosoftSurfacePro7i5.png",
        liked: false,
        cart: 0,
        description: [
            'диагональ: 12.3" (2736x1824)',
            'встроенная память: 128 ГБ, слот microSDXC',
            'оперативная память: 8 ГБ',
            'процессор: Intel Core i5 1035G4',
            'операционная система: Windows 10',
            'камеры: основная 8 МП, фронтальная 5 МП',
            'динамики: стерео',
            'беспроводные интерфейсы: WiFi 802.11ax, Bluetooth 5.0',
            'проводные интерфейсы: проприетарный, mini jack 3.5 mm',
            'время работы: 10.5 ч',
            'размеры: 292.1x201x8.5 мм, вес: 790 г',
        ]    
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 5,
        name: "Bosch HBF534EB0R",
        price: 330,
        image: "./images/products/BoschHBG578BS0R.jpg",
        liked: false,
        cart: 0,
        description: [
            'линейка: Serie 4',
            'установка: независимая',
            'объем: 66 л',
            'ШхГхВ: 59.40х54.80х59.50 см',
            'количество режимов нагрева: 8',
            'конвекция: есть',
            'гриль: есть',
            'максимальная температура: 275°C',
            'переключатели: поворотные, утапливаемые',
            'таймер: звуковой с отключением',
            'класс энергопотребления: A',
            'защита от детей: есть',
            'дисплей: есть',
            
        ]    
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 5,
        name: "Bosch HBF534EW0R",
        price: 430,
        image: "./images/products/BoschHBG578BS0R.jpg",
        liked: false,
        cart: 0,
        description: [
            'линейка: Serie 4',
            'установка: независимая',
            'объем: 66 л',
            'ШхГхВ: 59.40х54.80х59.50 см',
            'количество режимов нагрева: 8',
            'конвекция: есть',
            'гриль: есть',
            'максимальная температура: 275°C',
            'переключатели: поворотные, утапливаемые',
            'таймер: звуковой с отключением',
            'класс энергопотребления: A',
            'защита от детей: есть',
            'дисплей: есть',
            
        ]    
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 5,
        name: "Bosch HBG578BS0R",
        price: 450,
        image: "./images/products/BoschHBG578BS0R.jpg",
        liked: false,
        cart: 0,
        description: [
            'линейка: Serie 6',
            'установка: независимая',
            'объем: 71 л',
            'ШхГхВ: 59.40х54.80х59.50 см',
            'количество режимов нагрева: 7',
            'конвекция: есть',
            'гриль: есть',
            'максимальная температура: 275°C',
            'переключатели: поворотные, утапливаемые',
            'таймер: звуковой с отключением',
            'класс энергопотребления: A',
            'защита от детей: есть',
            'дисплей: есть',
            
        ]    
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 5,
        name: "Bosch HNG6764B6",
        price: 2700,
        image: "./images/products/BoschHNG6764B6.jpg",
        liked: false,
        cart: 0,
        description: [
            'линейка: Serie 8',
            'установка: независимая',
            'объем: 67 л',
            'ШхГхВ: 59.40х56х59.50 см',
            'функция СВЧ: есть',
            'количество режимов нагрева: 14',
            'конвекция: есть',
            'гриль: есть',
            'максимальная температура: 300°C',
            'очистка: пиролитическая',
            'переключатели: поворотные',
            'таймер: звуковой с отключением',
            'функция добавления пара: есть',
            'класс энергопотребления: A',
            'защита от детей: есть',
            'дисплей: есть',
                        
        ]    
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 5,
        name: "Bosch HBJ514EW0",
        price: 389,
        image: "./images/products/BoschHNG6764B6.jpg",
        liked: false,
        cart: 0,
        description: [
            'линейка: Serie 6',
            'установка: независимая',
            'объем: 66 л',
            'ШхГхВ: 59.40х56х59.50 см',
            'количество режимов нагрева: 8',
            'конвекция: есть',
            'гриль: есть',
            'максимальная температура: 275°C',
            'переключатели: поворотные тактовые, утапливаемые',
            'таймер: есть',
            'класс энергопотребления: A',
            'защита от детей: есть',
            'дисплей: есть',
                                    
        ]    
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 9,
        name: "LG GC-L247 CBDC",
        price: 1905,
        image: "./images/products/LGGC-L247.png",
        liked: false,
        cart: 0,
        description: [
            'ШхВхГ: 91.20х179х73.80 см',
            'общий объем: 601 л',
            'No Frost',
            'объем холодильной камеры: 405 л',
            'объем морозильной камеры: 196 л',
            'управление со смартфона',
            'инверторный компрессор',
            'количество компрессоров: один',
            'мощность замораживания: 12 кг/сутки',
        ]    
    },

        {
            id: Math.random().toString().slice(2, 10),
        brand_id: 9,
        name: "LG GC-Q22FTAKL",
        price: 189,
        image: "./images/products/LGGC-Q22FTAKLjpg.png",
        liked: false,
        cart: 0,
        description: [
            'ШхВхГ: 83.50х178.70х73.40 см',
            'общий объем: 458 л',
            'класс энергопотребления: A+',
            'No Frost',
            'объем холодильной камеры: 315 л',
            'объем морозильной камеры: 143 л',
            'управление со смартфона',
            'инверторный компрессор',
        ]    
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 9,
        name: "LG GA-B419 SWJL",
        price: 310,
        image: "./images/products/LGGA-B419SWJL.jpg",
        liked: false,
        cart: 0,
        description: [
            'ШхВхГ: 59.50х190.70х65.50 см',
            'общий объем: 302 л',
            'класс энергопотребления: A+',
            'No Frost',
            'объем холодильной камеры: 223 л',
            'объем морозильной камеры: 79 л',
            'инверторный компрессор',
            'количество компрессоров: один',
            'мощность замораживания: 9.3 кг/сутки',
            'возможность перевешивания дверей: ест',
        ]    
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 1,
        name: "Samsung RB38T7762SA",
        price: 1955,
        image: "./images/products/ХолодильникSamsungRB38T7762SA.png",
        liked: false,
        cart: 0,
        description: [
            'ШхВхГ: 59.50х203х65.80 см',
            'общий объем: 385 л',
            'класс энергопотребления: A++',
            'No Frost',
            'объем холодильной камеры: 273 л',
            'объем морозильной камеры: 112 л',
            'инверторный компрессор',
            'количество компрессоров: один',
            'мощность замораживания: 13 кг/сутки',
            'возможность перевешивания дверей: есть',
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 9,
        name: "LG GA-B499 YEQZ",
        price: 410,
        image: "./images/products/LGGA-B499YEQZ.png",
        liked: false,
        cart: 0,
        description: [
            'ШхВхГ: 59.50х200х68.80 см',
            'общий объем: 360 л',
            'класс энергопотребления: A++',
            'No Frost',
            'объем холодильной камеры: 226 л',
            'объем морозильной камеры: 105 л',
            'управление со смартфона',
            'инверторный компрессор',
            'количество компрессоров: один',
            'возможность перевеш',
        ]    
    },

    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 9,
        name: "LG GN-H702 HEHZ",
        price: 999,
        image: "./images/products/LGGN-H702HEHZ.png",
        liked: false,
        cart: 0,
        description: [
            'ШхВхГ: 78х180х73 см',
            'общий объем: 506 л',
            'класс энергопотребления: A++',
            'No Frost',
            'объем холодильной камеры: 376 л',
            'объем морозильной камеры: 130 л',
            'управление со смартфона',
            'инверторный компрессор',
            'количество компрессоров: один',
            'мощность замораживания: 5.5 кг/сутки',
        ]    
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 1,
        name: "Samsung RS54N3003EF",
        price: 1900,
        image: "./images/products/SamsungRS54N3003EF.png",
        liked: false,
        cart: 0,
        description: [
            'ШхВхГ: 59.50х203х65.80 см',
            'общий объем: 385 л',
            'класс энергопотребления: A++',
            'No Frost',
            'объем холодильной камеры: 273 л',
            'объем морозильной камеры: 112 л',
            'инверторный компрессор',
            'количество компрессоров: один',
            'мощность замораживания: 13 кг/сутки',
            'возможность перевешивания дверей: есть',   
        ]
    },
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 8,
        name: "Weissgauff EOV ",
        price: 278,
        image: "./images/products/WeissgauffEOV.jpg",
        liked: false,
        cart: 0,
        description: [
            'установка: независимая',
            'объем: 50 л',
            'ШхГхВ: 59.50х53.50х59.30 см',
            'количество режимов нагрева: 9',
            'конвекция: есть',
            'гриль: есть',
            'максимальная температура: 250°C',
            'очистка: гидролизная',
            'переключатели: поворотные',
            'таймер: звуковой',
            'класс энергопотребления: A',
        ]    
    },
    
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 8,
        name: "Weissgauff EOY 451 ",
        price: 305,
        image: "./images/products/WeissgauffEOY451.jpg",
        liked: false,
        cart: 0,
        description: [
            'установка: независимая',
            'объем: 55 л',
            'ШхГхВ: 59.50х53.50х59.30 см',
            'количество режимов нагрева: 12',
            'конвекция: есть',
            'гриль: есть',
            'максимальная температура: 300°C',
            'очистка: гидролизная',
            'переключатели: поворотные',
            'таймер: звуковой',
            'класс энергопотребления: A+',
        ]    
    },
    
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 8,
        name: "Weissgauff EOM 731",
        price: 345,
        image: "./images/products/WeissgauffEOM731PDW.jpg",
        liked: false,
        cart: 0,
        description: [
            'установка: независимая',
            'объем: 72 л',
            'ШхГхВ: 59.50х53.50х59.30 см',
            'количество режимов нагрева: 13',
            'конвекция: есть',
            'гриль: есть',
            'максимальная температура: 300°C',
            'очистка: гидролизная',
            'переключатели: поворотные',
            'защита от детей: есть',
            'дисплей: есть',
        ]    
    },

       
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 8,
        name: "Weissgauff EOV 29 PDX",
        price: 245,
        image: "./images/products/WeissgauffEOV29PDX.jpg",
        liked: false,
        cart: 0,
        description: [
            'установка: независимая',
            'объем: 60 л',
            'ШхГхВ: 59.50х53.50х59.30 см',
            'количество режимов нагрева: 9',
            'конвекция: есть',
            'гриль: есть',
            'максимальная температура: 250°C',
            'очистка: гидролизная',
            'переключатели: поворотные',
            'защита от детей: есть',
            'дисплей: есть',
        ]    
    },
    
    
    
    {
        id: Math.random().toString().slice(2, 10),
        brand_id: 8,
        name: "Weissgauff WCD 337",
        price: 760,
        image: "./images/products/WeissgauffWCD337NFX.png",
        liked: false,
        cart: 0,
        description: [
            'ШхВхГ: 79.50х180х61.20 см',
            'общий объем: 337 л',
            'класс энергопотребления: A+',
            'No Frost',
            'объем холодильной камеры: 225 л',
            'объем морозильной камеры: 112 л',
            'количество компрессоров: один',
            'мощность замораживания: 14 кг/сутки',
        ]    
    },
]

export { brands, products }




